name = "Flowergarden"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "825d513e65fb2f2025295e909ca0c8b1bacfbb226fbcdb804f853deaa2bf80ed"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
