name = "WTHIT Plugins"
filename = "wthit-plugins-1.0.4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/34431T56/versions/1.0.4/wthit-plugins-1.0.4.jar"
hash-format = "sha1"
hash = "358cabd278b9b128e0ee1a2befd31ac11918ab5d"

[update]
[update.modrinth]
mod-id = "34431T56"
version = "Rc2BDkIe"
